scoreboard players tag @e[type=Item] add CCIron {Item:{id:"minecraft:iron_ingot",Count:1b}}
execute @e[tag=CCIron] ~ ~ ~ detect ~ ~-.1 ~ crafting_table -1 scoreboard players tag @s add CCCreate
execute @e[tag=CCCreate] ~ ~ ~ setblock ~ ~-.1 ~ air
execute @e[tag=CCCreate] ~ ~ ~ summon minecraft:leash_knot ~ ~-.1 ~ {Tags:["CCCreate2"]}
kill @e[tag=CCCreate]

execute @e[tag=CCCreate2] ~ ~ ~ summon chest_minecart ~ ~-.5 ~ {Silent:1b,Invisible:1b,NoGravity:1b,CustomName:"Custom Crafter",Tags:["CC"],CustomDisplayTile:1,DisplayTile:"minecraft:crafting_table",DisplayOffset:5,Invulnerable:1b,Items:[{Slot:0,id:"minecraft:stained_glass_pane",Damage:7,Count:1b,tag:{display:{Name:"",Lore:["Mess with these slots to delete the minecart!","CC"]}}},{Slot:1,id:"minecraft:stained_glass_pane",Damage:7,Count:1b,tag:{display:{Name:"",Lore:["Mess with these slots to delete the minecart!","CC"]}}},{Slot:2,id:"minecraft:stained_glass_pane",Damage:7,Count:1b,tag:{display:{Name:"",Lore:["Mess with these slots to delete the minecart!","CC"]}}},{Slot:6,id:"minecraft:stained_glass_pane",Damage:7,Count:1b,tag:{display:{Name:"",Lore:["Mess with these slots to delete the minecart!","CC"]}}},{Slot:7,id:"minecraft:stained_glass_pane",Damage:7,Count:1b,tag:{display:{Name:"",Lore:["Mess with these slots to delete the minecart!","CC"]}}},{Slot:8,id:"minecraft:stained_glass_pane",Damage:7,Count:1b,tag:{display:{Name:"",Lore:["Mess with these slots to delete the minecart!","CC"]}}},{Slot:9,id:"minecraft:stained_glass_pane",Damage:7,Count:1b,tag:{display:{Name:"",Lore:["Mess with these slots to delete the minecart!","CC"]}}},{Slot:10,id:"minecraft:crafting_table",Count:1b},{Slot:11,id:"minecraft:stained_glass_pane",Damage:7,Count:1b,tag:{display:{Name:"",Lore:["Mess with these slots to delete the minecart!","CC"]}}},{Slot:15,id:"minecraft:stained_glass_pane",Damage:7,Count:1b,tag:{display:{Name:"",Lore:["Mess with these slots to delete the minecart!","CC"]}}},{Slot:17,id:"minecraft:stained_glass_pane",Damage:7,Count:1b,tag:{display:{Name:"",Lore:["Mess with these slots to delete the minecart!","CC"]}}},{Slot:18,id:"minecraft:stained_glass_pane",Damage:7,Count:1b,tag:{display:{Name:"",Lore:["Mess with these slots to delete the minecart!","CC"]}}},{Slot:19,id:"minecraft:stained_glass_pane",Damage:7,Count:1b,tag:{display:{Name:"",Lore:["Mess with these slots to delete the minecart!","CC"]}}},{Slot:20,id:"minecraft:stained_glass_pane",Damage:7,Count:1b,tag:{display:{Name:"",Lore:["Mess with these slots to delete the minecart!","CC"]}}},{Slot:24,id:"minecraft:stained_glass_pane",Damage:7,Count:1b,tag:{display:{Name:"",Lore:["Mess with these slots to delete the minecart!","CC"]}}},{Slot:25,id:"minecraft:stained_glass_pane",Damage:7,Count:1b,tag:{display:{Name:"",Lore:["Mess with these slots to delete the minecart!","CC"]}}},{Slot:26,id:"minecraft:stained_glass_pane",Damage:7,Count:1b,tag:{display:{Name:"",Lore:["Mess with these slots to delete the minecart!","CC"]}}}]}
execute @e[tag=CCCreate2] ~ ~ ~ summon armor_stand ~ ~-.5 ~ {Silent:1b,DisabledSlots:2031616,Small:1b,NoGravity:1b,Tags:["CC2"],Invisible:1,Invulnerable:1,NoBasePlate:1,ArmorItems:[{},{},{},{id:"minecraft:stone",Count:1b,tag:{display:{Lore:["CC"]}}}]}
scoreboard teams join CC @e[tag=CC]
kill @e[tag=CCCreate2]

scoreboard players tag @e[tag=CCIron] remove CCIron