execute @e[tag=CC] ~ ~ ~ tp @s @e[r=1,c=1,tag=CC2]

execute @e[tag=CC] ~ ~ ~ scoreboard players tag @e[tag=CC2,c=1,r=0] add CCStay
execute @e[tag=CC2] ~ ~ ~ scoreboard players tag @e[tag=CC,c=1,r=0] add CCStay2
scoreboard players tag @e[tag=CC] add CCStay3 {Items:[{Slot:0b,id:"minecraft:stained_glass_pane",Count:1b,tag:{display:{Lore:["Mess with these slots to delete the minecart!","CC"],Name:""}},Damage:7s},{Slot:1b,id:"minecraft:stained_glass_pane",Count:1b,tag:{display:{Lore:["Mess with these slots to delete the minecart!","CC"],Name:""}},Damage:7s},{Slot:2b,id:"minecraft:stained_glass_pane",Count:1b,tag:{display:{Lore:["Mess with these slots to delete the minecart!","CC"],Name:""}},Damage:7s},{Slot:6b,id:"minecraft:stained_glass_pane",Count:1b,tag:{display:{Lore:["Mess with these slots to delete the minecart!","CC"],Name:""}},Damage:7s},{Slot:7b,id:"minecraft:stained_glass_pane",Count:1b,tag:{display:{Lore:["Mess with these slots to delete the minecart!","CC"],Name:""}},Damage:7s},{Slot:8b,id:"minecraft:stained_glass_pane",Count:1b,tag:{display:{Lore:["Mess with these slots to delete the minecart!","CC"],Name:""}},Damage:7s},{Slot:9b,id:"minecraft:stained_glass_pane",Count:1b,tag:{display:{Lore:["Mess with these slots to delete the minecart!","CC"],Name:""}},Damage:7s},{Slot:11b,id:"minecraft:stained_glass_pane",Count:1b,tag:{display:{Lore:["Mess with these slots to delete the minecart!","CC"],Name:""}},Damage:7s},{Slot:15b,id:"minecraft:stained_glass_pane",Count:1b,tag:{display:{Lore:["Mess with these slots to delete the minecart!","CC"],Name:""}},Damage:7s},{Slot:17b,id:"minecraft:stained_glass_pane",Count:1b,tag:{display:{Lore:["Mess with these slots to delete the minecart!","CC"],Name:""}},Damage:7s},{Slot:18b,id:"minecraft:stained_glass_pane",Count:1b,tag:{display:{Lore:["Mess with these slots to delete the minecart!","CC"],Name:""}},Damage:7s},{Slot:19b,id:"minecraft:stained_glass_pane",Count:1b,tag:{display:{Lore:["Mess with these slots to delete the minecart!","CC"],Name:""}},Damage:7s},{Slot:20b,id:"minecraft:stained_glass_pane",Count:1b,tag:{display:{Lore:["Mess with these slots to delete the minecart!","CC"],Name:""}},Damage:7s},{Slot:24b,id:"minecraft:stained_glass_pane",Count:1b,tag:{display:{Lore:["Mess with these slots to delete the minecart!","CC"],Name:""}},Damage:7s},{Slot:25b,id:"minecraft:stained_glass_pane",Count:1b,tag:{display:{Lore:["Mess with these slots to delete the minecart!","CC"],Name:""}},Damage:7s},{Slot:26b,id:"minecraft:stained_glass_pane",Count:1b,tag:{display:{Lore:["Mess with these slots to delete the minecart!","CC"],Name:""}},Damage:7s}]}

execute @e[tag=CC2] ~ ~ ~ execute @s[tag=!CCStay] ~ ~ ~ summon Item ~ ~ ~ {Item:{id:"minecraft:iron_ingot",Count:1b},Motion:[0.0,0.3,0.0]}

execute @e[tag=CC2] ~ ~ ~ kill @s[tag=!CCStay]
execute @e[tag=CC] ~ ~ ~ kill @s[tag=!CCStay2]
execute @e[tag=CC] ~ ~ ~ kill @s[tag=!CCStay3]
scoreboard players tag @e[tag=CCStay] remove CCStay
scoreboard players tag @e[tag=CCStay2] remove CCStay2
scoreboard players tag @e[tag=CCStay3] remove CCStay3