scoreboard players set @e[score_RecipeID_min=1] RecipeID -1

scoreboard players set @e[tag=CCGo] RecipeID 1 {Items:[{Slot:3b,id:"minecraft:iron_block",Count:42b,Damage:0s},{Slot:4b,id:"minecraft:shulker_shell",Count:1b,Damage:0s},{Slot:5b,id:"minecraft:iron_block",Count:42b,Damage:0s},{Slot:10b,id:"minecraft:crafting_table",Count:1b,Damage:0s},{Slot:12b,id:"minecraft:shulker_shell",Count:1b,Damage:0s},{Slot:13b,id:"minecraft:beacon",Count:1b,Damage:0s},{Slot:14b,id:"minecraft:shulker_shell",Count:1b,Damage:0s},{Slot:21b,id:"minecraft:iron_block",Count:42b,Damage:0s},{Slot:22b,id:"minecraft:shulker_shell",Count:1b,Damage:0s},{Slot:23b,id:"minecraft:iron_block",Count:42b,Damage:0s}]}
scoreboard players set @e[tag=CCGo] RecipeID 1 {Items:[{Slot:3b,id:"minecraft:gold_block",Count:42b,Damage:0s},{Slot:4b,id:"minecraft:shulker_shell",Count:1b,Damage:0s},{Slot:5b,id:"minecraft:gold_block",Count:42b,Damage:0s},{Slot:10b,id:"minecraft:crafting_table",Count:1b,Damage:0s},{Slot:12b,id:"minecraft:shulker_shell",Count:1b,Damage:0s},{Slot:13b,id:"minecraft:beacon",Count:1b,Damage:0s},{Slot:14b,id:"minecraft:shulker_shell",Count:1b,Damage:0s},{Slot:21b,id:"minecraft:gold_block",Count:42b,Damage:0s},{Slot:22b,id:"minecraft:shulker_shell",Count:1b,Damage:0s},{Slot:23b,id:"minecraft:gold_block",Count:42b,Damage:0s}]}
scoreboard players set @e[tag=CCGo] RecipeID 1 {Items:[{Slot:3b,id:"minecraft:diamond_block",Count:42b,Damage:0s},{Slot:4b,id:"minecraft:shulker_shell",Count:1b,Damage:0s},{Slot:5b,id:"minecraft:diamond_block",Count:42b,Damage:0s},{Slot:10b,id:"minecraft:crafting_table",Count:1b,Damage:0s},{Slot:12b,id:"minecraft:shulker_shell",Count:1b,Damage:0s},{Slot:13b,id:"minecraft:beacon",Count:1b,Damage:0s},{Slot:14b,id:"minecraft:shulker_shell",Count:1b,Damage:0s},{Slot:21b,id:"minecraft:diamond_block",Count:42b,Damage:0s},{Slot:22b,id:"minecraft:shulker_shell",Count:1b,Damage:0s},{Slot:23b,id:"minecraft:diamond_block",Count:42b,Damage:0s}]}
scoreboard players set @e[tag=CCGo] RecipeID 1 {Items:[{Slot:3b,id:"minecraft:emerald_block",Count:42b,Damage:0s},{Slot:4b,id:"minecraft:shulker_shell",Count:1b,Damage:0s},{Slot:5b,id:"minecraft:emerald_block",Count:42b,Damage:0s},{Slot:10b,id:"minecraft:crafting_table",Count:1b,Damage:0s},{Slot:12b,id:"minecraft:shulker_shell",Count:1b,Damage:0s},{Slot:13b,id:"minecraft:beacon",Count:1b,Damage:0s},{Slot:14b,id:"minecraft:shulker_shell",Count:1b,Damage:0s},{Slot:21b,id:"minecraft:emerald_block",Count:42b,Damage:0s},{Slot:22b,id:"minecraft:shulker_shell",Count:1b,Damage:0s},{Slot:23b,id:"minecraft:emerald_block",Count:42b,Damage:0s}]}
entitydata @e[score_RecipeID_min=1,score_RecipeID=1] {Items:[{Slot:0b,id:"minecraft:stained_glass_pane",Count:1b,tag:{display:{Lore:["Mess with these slots to delete the minecart!","CC"],Name:""}},Damage:7s},{Slot:1b,id:"minecraft:stained_glass_pane",Count:1b,tag:{display:{Lore:["Mess with these slots to delete the minecart!","CC"],Name:""}},Damage:7s},{Slot:2b,id:"minecraft:stained_glass_pane",Count:1b,tag:{display:{Lore:["Mess with these slots to delete the minecart!","CC"],Name:""}},Damage:7s},{Slot:6b,id:"minecraft:stained_glass_pane",Count:1b,tag:{display:{Lore:["Mess with these slots to delete the minecart!","CC"],Name:""}},Damage:7s},{Slot:7b,id:"minecraft:stained_glass_pane",Count:1b,tag:{display:{Lore:["Mess with these slots to delete the minecart!","CC"],Name:""}},Damage:7s},{Slot:8b,id:"minecraft:stained_glass_pane",Count:1b,tag:{display:{Lore:["Mess with these slots to delete the minecart!","CC"],Name:""}},Damage:7s},{Slot:9b,id:"minecraft:stained_glass_pane",Count:1b,tag:{display:{Lore:["Mess with these slots to delete the minecart!","CC"],Name:""}},Damage:7s},{Slot:10b,id:"minecraft:crafting_table",Count:1b,Damage:0s},{Slot:11b,id:"minecraft:stained_glass_pane",Count:1b,tag:{display:{Lore:["Mess with these slots to delete the minecart!","CC"],Name:""}},Damage:7s},{Slot:15b,id:"minecraft:stained_glass_pane",Count:1b,tag:{display:{Lore:["Mess with these slots to delete the minecart!","CC"],Name:""}},Damage:7s},{Slot:16b,id:"minecraft:repeating_command_block",Count:1b,tag:{display:{Lore:["Effect: Speed","Tap shift while holding to change effect."],Name:"Portable Beacon"}},Damage:0s},{Slot:17b,id:"minecraft:stained_glass_pane",Count:1b,tag:{display:{Lore:["Mess with these slots to delete the minecart!","CC"],Name:""}},Damage:7s},{Slot:18b,id:"minecraft:stained_glass_pane",Count:1b,tag:{display:{Lore:["Mess with these slots to delete the minecart!","CC"],Name:""}},Damage:7s},{Slot:19b,id:"minecraft:stained_glass_pane",Count:1b,tag:{display:{Lore:["Mess with these slots to delete the minecart!","CC"],Name:""}},Damage:7s},{Slot:20b,id:"minecraft:stained_glass_pane",Count:1b,tag:{display:{Lore:["Mess with these slots to delete the minecart!","CC"],Name:""}},Damage:7s},{Slot:24b,id:"minecraft:stained_glass_pane",Count:1b,tag:{display:{Lore:["Mess with these slots to delete the minecart!","CC"],Name:""}},Damage:7s},{Slot:25b,id:"minecraft:stained_glass_pane",Count:1b,tag:{display:{Lore:["Mess with these slots to delete the minecart!","CC"],Name:""}},Damage:7s},{Slot:26b,id:"minecraft:stained_glass_pane",Count:1b,tag:{display:{Lore:["Mess with these slots to delete the minecart!","CC"],Name:""}},Damage:7s}]}

execute @e[score_RecipeID_min=1] ~ ~ ~ playsound minecraft:block.anvil.use block @a[r=10] ~ ~ ~ .2
execute @e[score_RecipeID_min=1] ~ ~ ~ playsound minecraft:block.shulker_box.close block @a[r=10] ~ ~ ~ .5
execute @e[score_RecipeID_min=1] ~ ~ ~ playsound minecraft:block.shulker_box.open block @a[r=10] ~ ~ ~ .5

scoreboard players set @e[score_RecipeID_min=1] RecipeID -1